# Generated by Django 4.1.1 on 2022-09-24 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renecfans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_government', models.CharField(max_length=60, unique=True)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mystate', to='renecfans.states')),
            ],
        ),
    ]
