# Generated by Django 4.1.1 on 2022-09-25 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renecfans', '0002_lg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contributors',
            new_name='Contributor',
        ),
        migrations.RenameModel(
            old_name='Lg',
            new_name='Local_government',
        ),
        migrations.RenameModel(
            old_name='Peoples',
            new_name='People',
        ),
        migrations.RenameModel(
            old_name='States',
            new_name='State',
        ),
    ]
