# Generated by Django 4.1.1 on 2022-09-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renecfans', '0003_rename_contributors_contributor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='lga',
        ),
    ]
