# Generated by Django 4.1.1 on 2022-10-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renecfans', '0004_remove_state_lga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='trx_wallet',
        ),
    ]
